### ISSUE TITLE
Cannot capture exception when accessing element properties with selenide

### ISSUE THREAD

**Issue by maxwu** [maxwu/Genre-Clawer#1]
With SelenideElement proxy, when accessing the properties, the WebElement was searched with driver but it threw exception instead of returning null.

```java
// Get Element within Page Object
return $("#rso div._uX div._XWk");
```

```java
// Extract data with Page Object
public List<String> getGenres(){
        List<String> genres;
        try{
            genres = Arrays.asList(getGenreDiv().getText().split("/"));
        }catch (Exception e){
            genres = new ArrayList<>(Arrays.asList("NA"));
        }
        logger.debug("Genres are: " + genres.stream().collect(Collectors.joining()));
        return genres;
    }
```

In either place, the exception cannot be directly captured. Record the reproducing cmd as usual `me.maxwu.selenide.BillboardTop100GenreTest`. 

```
testTop10Genres(me.maxwu.selenide.BillboardTop100GenreTest)  Time elapsed: 39.793 sec  <<< FAILURE!
Element not found {#rso div._uX div._XWk}
Expected: exist
Screenshot: file:/Users/maxwu/devel/selenide-toy/target/1489635016323.0.png
Timeout: 4 s.
Caused by: NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#rso div._uX div._XWk"}
	at 
	//... ... 
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#rso div._uX div._XWk"}
  (Session info: chrome=58.0.3029.19)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.1.0', revision: 'b94c902', time: '2017-02-16 12:21:31 -0800'
System info: host: 'MaxWudeMacBook-Pro.local', ip: 'fe80:0:0:0:aebc:32ff:fe9a:5a9d%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9), userDataDir=/var/folders/gq/kylyhbzd2wxgp8j_dm031t8h0000gn/T/.org.chromium.Chromium.Ns9Vla}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=58.0.3029.19, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 6b4fb12f6d032af2908e5148700531cd
*** Element info: {Using=css selector, value=#rso div._uX div._XWk}
	at sun.reflect.GeneratedConstructorAccessor8.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:465)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:430)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:360)
	at com.codeborne.selenide.impl.WebElementSelector.findElement(WebElementSelector.java:28)
	at com.codeborne.selenide.impl.ElementFinder.getWebElement(ElementFinder.java:56)
	at com.codeborne.selenide.commands.GetText.execute(GetText.java:13)
	at com.codeborne.selenide.commands.GetText.execute(GetText.java:8)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:140)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:86)
	... 36 more
```

**Comment by maxwu** [comment]
An open issue with selenide described similar feature-request, https://github.com/codeborne/selenide/issues/259 
However, it is another request to make a null return instead of exception. It seems not a better solution since most test stuffs depend on throwable types.

**Comment by maxwu** [comment]
Searching google and found https://github.com/codeborne/selenide/issues/218 
Therefore we can capture the Throwable when first accessing the WebElement properties to decide the following branch. When selenide is used by web clawer,  such throwables as UIAssertionError are handled by encapsulated page objects.

**Comment by maxwu** [comment]
It is resolved, just reopen to keep an eye on summary writing.
Output is still a step of learning to complete.
